service: appointment-operations
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query"
        - "dynamodb:BatchWriteItem"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${file(config.json):DYNAMODB_TABLE}"
plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-typescript
#Local DynamoDb configuration
custom:
  dynamodb:
    stages:
      - ${file(config.json):STAGE}
    start: 
      port: 8000
      migrate: true # create the tables
      # inMemory: true
      onStart: true

functions:
  getAppointments:
    handler: src/functions/appointments/getAvailableAppointments.handler
    events:
      - http:
          path: appointment/employee/{employeeId}/date/{date}
          method: get
  generateAppointments:
    handler: src/functions/appointments/generateAppointments.hanler
    events:
      - http:
          path: appointment
          method: post
  scheduleAppointment:
    handler: src/functions/appointments/scheduleAppointment.handler
    events:
      - http:
          path: appointment
          method: put
  queryShopsByRadius:
    handler: src/functions/shops/queryShopsByRadius.handler
    events:
      - http:
          path: shops
          method: get
  createShop:
    handler: src/functions/shops/createShop.handler
    events:
      - http:
          path: shops
          method: post
resources:
  Resources:
    AppointmentTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "employeeId"
          AttributeType: "S"
        - AttributeName: "appointmentStartTime"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "employeeId"
          KeyType: "HASH"
        - AttributeName: appointmentStartTime
          KeyType: "RANGE"  
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${file(config.json):DYNAMODB_TABLE}
    ShopTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "N"
        - AttributeName: "rangeKey"
          AttributeType: "S"
        - AttributeName: "geohash"
          AttributeType: "N"
        KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "rangeKey"
          KeyType: "RANGE"  
        GlobalSecondaryIndexes:
          - IndexName: "rangeKey-index"
            KeySchema:
              - AttributeName: "rangeKey"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        LocalSecondaryIndexes:
        - IndexName: "geohash-index"
          KeySchema:
          - AttributeName: "hashKey"
            KeyType: "HASH"
          - AttributeName: "geohash"
            KeyType: "RANGE"  
          Projection:
              ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${file(config.json):PRIMO_SHOP_TABLE}
