import {
    attribute,
    autoGeneratedHashKey,
    hashKey,
    rangeKey,
    table
} from "@aws/dynamodb-data-mapper-annotations";
import config from "../../config.json";
import { Appointment } from "./appointment";
const tableName = config.PRIMO_CANCELLED_APPOINTMENT_TABLE;

@table(tableName)
export class CancelledAppointment {
    @autoGeneratedHashKey()
    id?:string;
    @attribute()
    appointmentStartTime?: string;
    @attribute()
    employeeId?: string;
    @attribute()
    userId?: string;
    @attribute()
    serviceId?: string;
    @attribute()
    cancelledOn?: string;
    @attribute()
    cancelledBy?: string;
    @attribute()
    shopId?: string;


    static create(appointment: Appointment, initiator: string, shopId: string): CancelledAppointment {
        const cancelledAppointment = new CancelledAppointment();
        cancelledAppointment.appointmentStartTime = appointment.appointmentStartTime;
        cancelledAppointment.userId = appointment.userId;
        cancelledAppointment.cancelledBy = initiator;
        cancelledAppointment.cancelledOn = new Date().toISOString();
        cancelledAppointment.serviceId = appointment.serviceId;
        cancelledAppointment.employeeId = appointment.employeeId;
        cancelledAppointment.shopId = shopId;
        return cancelledAppointment;
    }

}