import {
    attribute,
    autoGeneratedHashKey,
    table
} from "@aws/dynamodb-data-mapper-annotations";
import config from "../../config.json";
const tableName = config.PRIMO_SERVICE_TABLE;

@table(tableName)
export class PrimoService {
    @autoGeneratedHashKey()
    serviceId?: string;
    @attribute()
    serviceName?: string;
}